// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m0hit2409/transactions-service/internal/repository (interfaces: OperationTypeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_operation_type_repository.go -package=mocks github.com/m0hit2409/transactions-service/internal/repository OperationTypeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/m0hit2409/transactions-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOperationTypeRepository is a mock of OperationTypeRepository interface.
type MockOperationTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOperationTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockOperationTypeRepositoryMockRecorder is the mock recorder for MockOperationTypeRepository.
type MockOperationTypeRepositoryMockRecorder struct {
	mock *MockOperationTypeRepository
}

// NewMockOperationTypeRepository creates a new mock instance.
func NewMockOperationTypeRepository(ctrl *gomock.Controller) *MockOperationTypeRepository {
	mock := &MockOperationTypeRepository{ctrl: ctrl}
	mock.recorder = &MockOperationTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationTypeRepository) EXPECT() *MockOperationTypeRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockOperationTypeRepository) FindByID(ctx context.Context, id int) (domain.OperationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.OperationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOperationTypeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOperationTypeRepository)(nil).FindByID), ctx, id)
}
